# Generated by Django 5.0.3 on 2024-04-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem2app', '0002_alter_coin_throw_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('biography', models.TextField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
